// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSrSvG0HiFWf817cFrqFxNqIP2KykywxE',
    appId: '1:738716952308:web:c421bc8f4c0811cb32a0a1',
    messagingSenderId: '738716952308',
    projectId: 'efood-app-492fe',
    authDomain: 'efood-app-492fe.firebaseapp.com',
    storageBucket: 'efood-app-492fe.appspot.com',
    measurementId: 'G-MT5YD7X3ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCypvfaGAuTdVFrpENnFzc39JA_1BwlTCU',
    appId: '1:738716952308:android:2fe8683e928ffb6632a0a1',
    messagingSenderId: '738716952308',
    projectId: 'efood-app-492fe',
    storageBucket: 'efood-app-492fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCKA25h3p9LAl0_8-Z9B3gXyXweBZQ1AM',
    appId: '1:738716952308:ios:bd904582144ac8a132a0a1',
    messagingSenderId: '738716952308',
    projectId: 'efood-app-492fe',
    storageBucket: 'efood-app-492fe.appspot.com',
    iosBundleId: 'com.kazungudev.boilerplateFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCKA25h3p9LAl0_8-Z9B3gXyXweBZQ1AM',
    appId: '1:738716952308:ios:a16ef5641000c18f32a0a1',
    messagingSenderId: '738716952308',
    projectId: 'efood-app-492fe',
    storageBucket: 'efood-app-492fe.appspot.com',
    iosBundleId: 'com.kazungudev.boilerplateFlutter.RunnerTests',
  );
}
